import type { Prompt } from "../types";

type SeedPrompt = Omit<
  Prompt,
  "createdAt" | "updatedAt" | "userId" | "projectId"
> & { createdDaysAgo: number };

type Model = "midjourney" | "stable-diffusion" | "flux" | "dall-e-3";
type Pattern = "mesh" | "orbs" | "rings" | "waves" | "grid" | "aurora";

const PATTERNS: Pattern[] = ["mesh", "orbs", "rings", "waves", "grid", "aurora"];
const AUTHORS = ["curator", "aria", "kenji", "luna", "max"] as const;
const RATINGS = [4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0] as const;
const OFFICIAL_URLS = [
  "https://docs.midjourney.com",
  "https://openai.com/dall-e-3",
  "https://blackforestlabs.ai",
  "https://stability.ai",
];

const MODELS: Array<{
  model: Model;
  vendor: string;
  params: Record<string, string | number>;
}> = [
  { model: "midjourney", vendor: "Midjourney", params: { aspect: "16:9", version: "v6", stylize: 250 } },
  { model: "stable-diffusion", vendor: "Stability AI", params: { steps: 30, cfg: 7, sampler: "DPM++ 2M Karras" } },
  { model: "flux", vendor: "Black Forest Labs", params: { guidance: 3.5, steps: 28 } },
  { model: "dall-e-3", vendor: "OpenAI", params: { quality: "hd", style: "vivid" } },
];

interface Core {
  title: string;
  content: string;
  contentZh: string;
  tags: string[];
  model: Model;
}

const cores: Core[] = [
  // ===== 人像摄影 1-10 =====
  { title: "霓虹雨夜东京人像", content: "cinematic portrait of a woman standing under neon signs in rainy tokyo alley, reflective puddles, bokeh lights, teal magenta grade, 85mm f1.4, shallow depth of field, film grain --ar 4:5 --v 6 --stylize 250", contentZh: "电影感女性肖像，站在霓虹灯下的雨夜东京小巷，倒映的水洼，灯光散景，青色与品红色调，85mm f1.4 镜头，浅景深，胶片颗粒", tags: ["人像", "赛博朋克", "电影感", "夜景"], model: "midjourney" },
  { title: "高原牧民沧桑肖像", content: "environmental portrait of a tibetan elder with weathered face, prayer beads, mountain plateau background, golden hour side light, leica 50mm, deep wrinkles, soulful eyes, documentary realism", contentZh: "环境肖像，藏族老人沧桑面庞，手转佛珠，高原山脉背景，黄金时刻侧光，徕卡 50mm 镜头，深刻皱纹，深邃眼神，纪实写实", tags: ["人像", "纪实", "高原", "老人"], model: "flux" },
  { title: "复古港风街头人像", content: "90s hong kong street portrait, woman in vintage cheongsam, wet market alley, neon glow, kodak portra 400 film, nostalgic warm tones, cinematic, wong kar-wai style", contentZh: "九十年代港风街头人像，女子身着复古旗袍，湿货市场小巷，霓虹微光，柯达 Portra 400 胶片，怀旧暖色调，电影感，王家卫风格", tags: ["人像", "港风", "复古", "胶片"], model: "stable-diffusion" },
  { title: "童真笑容自然光人像", content: "natural light portrait of a laughing child in a sunlit wheat field, soft golden backlight, flyaway hair, candid emotion, 50mm, warm and tender mood, fine art photography", contentZh: "自然光人像，麦田中大笑的孩童，柔和金色逆光，飘动的发丝，抓拍的情绪，50mm 镜头，温暖柔情的氛围，艺术摄影", tags: ["人像", "儿童", "自然光", "温馨"], model: "dall-e-3" },
  { title: "黑白极简人像", content: "minimalist black and white portrait, single elderly man against concrete wall, dramatic rembrandt lighting, deep shadows, leica monochrom, fine art, high contrast --ar 4:5 --v 6", contentZh: "极简黑白人像，独坐老人靠在混凝土墙前，戏剧化伦勃朗光，深邃阴影，徕卡黑白机，艺术摄影，高对比", tags: ["人像", "黑白", "极简", "艺术"], model: "midjourney" },
  { title: "商务高管正式肖像", content: "corporate executive portrait of a confident woman in navy suit, clean studio background, soft key light with rim, shot on hasselblad 100mm, sharp eyes, professional retouching, magazine quality", contentZh: "企业高管肖像，自信的女性身着深蓝西装，干净影棚背景，柔主光加轮廓光，哈苏 100mm 镜头拍摄，眼神锐利，专业修图，杂志品质", tags: ["人像", "商务", "正式", "影棚"], model: "flux" },
  { title: "雨中漫步情绪人像", content: "moody portrait of a woman walking in rain under transparent umbrella, melancholic expression, soft mist, desaturated cool tones, cinematic, shot on 85mm f1.2, dreamy bokeh", contentZh: "情绪人像，女子撑透明伞雨中漫步，忧郁神情，柔和雾气，去饱和冷色调，电影感，85mm f1.2 镜头，梦幻散景", tags: ["人像", "情绪", "雨景", "电影感"], model: "stable-diffusion" },
  { title: "民族盛装人像", content: "portrait of a young woman in traditional mongolian festival robe, silver headdress, vast grassland, blue sky, natural daylight, vibrant ethnic patterns, national geographic style", contentZh: "人像，年轻女子身着蒙古族节日盛装，银饰头冠，辽阔草原，蔚蓝天空，自然日光，鲜艳民族纹样，国家地理风格", tags: ["人像", "民族", "蒙古", "纪实"], model: "dall-e-3" },
  { title: "黄昏逆光少女", content: "backlit portrait of a teenage girl at sunset, lens flare, flowing dress, dreamy haze, warm orange glow, candid smile, 135mm, shallow dof --ar 4:5 --v 6 --stylize 300", contentZh: "黄昏逆光少女肖像，镜头光晕，飘动连衣裙，梦幻薄雾，温暖橙色光辉，自然微笑，135mm 镜头，浅景深", tags: ["人像", "逆光", "黄昏", "少女"], model: "midjourney" },
  { title: "舞台聚光舞者肖像", content: "dramatic stage portrait of a ballet dancer mid-pose, single spotlight, dust particles in light beam, dark background, sweat and tension, 85mm, high contrast monochrome", contentZh: "戏剧化舞台肖像，芭蕾舞者定格瞬间，单一聚光灯，光束中的尘埃微粒，暗色背景，汗水与张力，85mm 镜头，高对比单色", tags: ["人像", "舞蹈", "舞台", "黑白"], model: "flux" },
  // ===== 风景 11-20 =====
  { title: "张家界云海奇峰", content: "epic landscape of zhangjiajie sandstone pillars emerging from sea of clouds, golden sunrise, mist drifting between peaks, cinematic wide angle, ultra detailed, 8k --ar 16:9 --v 6 --stylize 400", contentZh: "史诗级风景，张家界砂岩石柱从云海中拔地而起，金色日出，雾气在峰林间流动，电影感广角，超精细，8K", tags: ["风景", "山水", "云海", "日出"], model: "midjourney" },
  { title: "冰岛极光瀑布", content: "icelandic waterfall under vivid aurora borealis, snow capped mountains, long exposure silky water, starry sky, reflections in still pool, national geographic photography, 8k", contentZh: "冰岛瀑布上空绚烂极光，雪山顶，长曝光丝滑水流，星空，倒映在静谧水潭，国家地理摄影，8K", tags: ["风景", "极光", "瀑布", "冰岛"], model: "flux" },
  { title: "托斯卡纳田园秋色", content: "tuscany countryside in autumn, rolling hills, cypress trees, golden light, stone farmhouse, vineyards, warm color palette, fine art landscape photography, ultra detailed", contentZh: "秋日托斯卡纳田园，起伏山丘，柏树，金色光线，石砌农舍，葡萄园，温暖色调，艺术风景摄影，超精细", tags: ["风景", "田园", "秋色", "托斯卡纳"], model: "stable-diffusion" },
  { title: "富士山樱花湖景", content: "mount fuji reflected in a calm lake, cherry blossom petals drifting, soft pink sky at dawn, traditional japanese aesthetic, serene, ultra detailed, peaceful mood", contentZh: "富士山倒映于平静湖面，樱花花瓣飘落，黎明柔和粉色天空，传统日式美学，宁静，超精细，平和氛围", tags: ["风景", "富士山", "樱花", "日式"], model: "dall-e-3" },
  { title: "撒哈拉星空沙丘", content: "sahara desert dunes under milky way, lone camel caravan silhouette, star trails, deep blue night sky, golden sand curves, long exposure, awe inspiring --ar 16:9 --v 6", contentZh: "撒哈拉沙漠沙丘上的银河，孤独骆驼商队剪影，星轨，深蓝夜空，金色沙丘曲线，长曝光，令人敬畏", tags: ["风景", "沙漠", "星空", "延时"], model: "midjourney" },
  { title: "挪威峡湾晨雾", content: "norwegian fjord at dawn, low clouds drifting over mirror still water, steep green cliffs, small red cabin, soft pastel light, serene, ultra realistic, 8k landscape", contentZh: "黎明时分的挪威峡湾，低云飘过镜面般静止的水面，陡峭翠绿悬崖，红色小木屋，柔和粉彩光线，宁静，超写实，8K 风景", tags: ["风景", "峡湾", "晨雾", "北欧"], model: "flux" },
  { title: "秋日红枫林间小径", content: "winding forest path covered in fallen red maple leaves, sun rays filtering through canopy, misty morning, vibrant autumn colors, fairy tale atmosphere, photorealistic", contentZh: "蜿蜒的林间小径铺满红色枫叶，阳光透过树冠洒下光柱，晨雾弥漫，鲜艳秋色，童话氛围，照片级写实", tags: ["风景", "秋色", "森林", "光影"], model: "stable-diffusion" },
  { title: "热带海滩落日", content: "tropical beach sunset, palm trees silhouettes, turquoise waves, vibrant orange and purple sky, hammock, peaceful vacation mood, vivid colors, ultra detailed", contentZh: "热带海滩落日，棕榈树剪影，碧绿海浪，绚烂橙紫色天空，吊床，宁静度假氛围，鲜艳色彩，超精细", tags: ["风景", "海滩", "落日", "热带"], model: "dall-e-3" },
  { title: "川西高原花海", content: "vast plateau flower field in western sichuan, snow mountains in distance, blue sky with dramatic clouds, colorful wildflowers, golden hour, travel photography --ar 16:9 --v 6", contentZh: "川西高原辽阔花海，远处雪山，蓝天戏剧云，五彩野花，黄金时刻，旅行摄影", tags: ["风景", "花海", "高原", "川西"], model: "midjourney" },
  { title: "雷暴草原闪电", content: "dramatic prairie thunderstorm, lightning bolt striking across dark storm clouds, golden wheat field in foreground, high contrast, raw power of nature, ultra detailed", contentZh: "戏剧化草原雷暴，闪电划过暗黑风暴云，前景金色麦田，高对比，自然原始力量，超精细", tags: ["风景", "雷暴", "闪电", "草原"], model: "flux" },
  // ===== 动漫 21-30 =====
  { title: "新海诚风夕阳车站", content: "anime background art in makoto shinkai style, rural train station at sunset, glowing clouds, lens flare, detailed wires and grass, melancholic mood --ar 16:9 --v 6 --niji 6", contentZh: "新海诚风格动漫背景，乡村车站夕阳，发光云彩，镜头光晕，精细电线与草丛，忧郁氛围", tags: ["动漫", "新海诚", "夕阳", "场景"], model: "midjourney" },
  { title: "哥特萝莉角色立绘", content: "1girl, silver hair, red eyes, gothic lolita dress, intricate lace, holding glowing crystal, dramatic backlight, cherry blossoms, anime key visual, masterpiece, best quality, ultra detailed", contentZh: "1girl，银发红眼，哥特萝莉裙，精致蕾丝，手持发光水晶，戏剧化逆光，樱花，动漫主视觉，杰作，最佳品质，超精细", tags: ["二次元", "立绘", "哥特", "角色"], model: "stable-diffusion" },
  { title: "宫崎骏风龙猫森林", content: "studio ghibli inspired forest scene, giant ancient tree, soft sunlight through leaves, small creatures, lush green, hand painted watercolor texture, nostalgic and warm", contentZh: "吉卜力风格森林场景，巨型古树，柔和阳光穿过树叶，小生物，葱郁绿意，手绘水彩质感，怀旧温暖", tags: ["动漫", "吉卜力", "森林", "治愈"], model: "flux" },
  { title: "赛博风女骑士立绘", content: "anime key visual of a female knight in glowing cyber armor, holographic sword, neon city background, dynamic pose, vivid colors, sharp linework, ultra detailed illustration", contentZh: "动漫主视觉，身着发光赛博铠甲的女骑士，全息之剑，霓虹城市背景，动态姿势，鲜艳色彩，锐利线条，超精细插画", tags: ["二次元", "立绘", "赛博", "骑士"], model: "dall-e-3" },
  { title: "京都和服少女", content: "anime girl in floral kimono walking through kyoto torii gates, falling maple leaves, soft sunset, studio ghibli style, warm palette, detailed background --ar 9:16 --v 6 --niji 6", contentZh: "动漫少女身着花卉和服走过京都鸟居，飘落枫叶，柔和夕阳，吉卜力风格，暖色调，精细背景", tags: ["动漫", "和服", "京都", "少女"], model: "midjourney" },
  { title: "机甲驾驶员特写", content: "1boy, mecha pilot, flight suit, cockpit interior, holographic displays, intense expression, dramatic lighting, anime style, cinematic, highly detailed, masterpiece", contentZh: "1boy，机甲驾驶员，飞行服，驾驶舱内部，全息显示屏，坚毅神情，戏剧化光影，动漫风格，电影感，超精细，杰作", tags: ["二次元", "机甲", "特写", "科幻"], model: "stable-diffusion" },
  { title: "废土少女与机械犬", content: "anime illustration of a girl with backpack walking with robotic dog through post-apocalyptic ruins, overgrown plants, soft golden light, hopeful mood, detailed, cinematic", contentZh: "动漫插画，背包少女与机械犬穿行末日废墟，蔓延的植物，柔和金色光线，充满希望的氛围，精细，电影感", tags: ["动漫", "废土", "少女", "机械"], model: "flux" },
  { title: "魔法学院星空图书馆", content: "anime fantasy library with floating books, glowing magic circles, starry domed ceiling, student reading, warm candlelight, intricate architecture, studio ghibli mood", contentZh: "动漫奇幻图书馆，悬浮书籍，发光魔法阵，星空穹顶，学生阅读，温暖烛光，繁复建筑，吉卜力氛围", tags: ["动漫", "奇幻", "图书馆", "魔法"], model: "dall-e-3" },
  { title: "赛博朋克女黑客", content: "anime girl hacker in neon lit room, multiple holographic screens, glowing code, cyberpunk aesthetic, purple teal lighting, detailed tech, key visual --ar 16:9 --v 6 --niji 6", contentZh: "动漫女黑客在霓虹房间，多个全息屏幕，发光代码，赛博朋克美学，紫青光线，精细科技元素，主视觉", tags: ["动漫", "赛博朋克", "黑客", "立绘"], model: "midjourney" },
  { title: "巫女雪景祈福", content: "1girl, miko shrine maiden, red hakama, snow falling, lantern light, torii gate, serene expression, anime style, soft colors, masterpiece, best quality, ultra detailed", contentZh: "1girl，巫女，红色袴，飘雪，灯笼光，鸟居，宁静神情，动漫风格，柔和色彩，杰作，最佳品质，超精细", tags: ["二次元", "巫女", "雪景", "神社"], model: "stable-diffusion" },
  // ===== 概念艺术 31-40 =====
  { title: "水晶凤凰概念设计", content: "creature concept art, majestic phoenix made of crystal and fire, intricate glowing scales, embers, dark fantasy, foggy, by greg rutkowski, artstation, highly detailed --ar 3:4 --v 6 --stylize 600", contentZh: "生物概念艺术，由水晶与火焰构成的雄伟凤凰，精致发光鳞片，余烬，暗黑奇幻，雾气，Greg Rutkowski 风格，ArtStation，超精细", tags: ["概念艺术", "奇幻", "凤凰", "生物"], model: "midjourney" },
  { title: "末日避难所场景设计", content: "post-apocalyptic underground bunker concept, rusty machinery, dim fluorescent lights, survival gear, gritty atmosphere, matte painting, cinematic, detailed, video game art", contentZh: "末日地下避难所概念设计，锈蚀机械，昏暗荧光灯，生存装备，粗粝氛围，哑光绘画，电影感，精细，游戏美术", tags: ["概念艺术", "末日", "场景", "游戏"], model: "flux" },
  { title: "巨龙盘踞金币山", content: "concept art of an ancient dragon coiled on mountain of gold coins, vast cavern, shafts of light, scales shimmering, epic fantasy, detailed, trending on artstation", contentZh: "概念艺术，远古巨龙盘踞金币山，巨大洞穴，光柱，鳞片闪烁，史诗奇幻，精细，ArtStation 热门", tags: ["概念艺术", "巨龙", "奇幻", "洞穴"], model: "stable-diffusion" },
  { title: "悬浮未来城市概念", content: "concept art of a futuristic floating city, anti-gravity platforms, waterfalls into clouds, sleek architecture, flying vehicles, golden hour, sci-fi, highly detailed", contentZh: "概念艺术，未来悬浮城市，反重力平台，瀑布落入云海，流线建筑，飞行载具，黄金时刻，科幻，超精细", tags: ["概念艺术", "未来城市", "科幻", "悬浮"], model: "dall-e-3" },
  { title: "黑暗魔王王座场景", content: "dark lord seated on obsidian throne, lava cracks, glowing eyes, armored generals, ominous red sky, epic scale, fantasy concept art, cinematic --ar 16:9 --v 6 --stylize 500", contentZh: "黑暗魔王端坐黑曜石王座，岩浆裂缝，发光双眼，铠甲将领，不祥红天，史诗规模，奇幻概念艺术，电影感", tags: ["概念艺术", "奇幻", "魔王", "史诗"], model: "midjourney" },
  { title: "外星丛林生态设计", content: "alien jungle concept art, bioluminescent plants, strange flora, giant mushroom trees, floating spores, two moons in sky, otherworldly, science fiction, detailed", contentZh: "外星丛林概念艺术，生物发光植物，奇异花卉，巨型蘑菇树，漂浮孢子，天空两轮明月，异星感，科幻，精细", tags: ["概念艺术", "外星", "生态", "科幻"], model: "flux" },
  { title: "蒸汽朋克飞艇港口", content: "steampunk airship harbor concept, brass and copper vessels, gears and propellers, victorian industrial, foggy dock, warm lamp light, detailed matte painting, artstation", contentZh: "蒸汽朋克飞艇港口概念设计，黄铜与紫铜飞船，齿轮与螺旋桨，维多利亚工业风，雾蒙码头，暖色灯光，精细哑光绘画，ArtStation", tags: ["概念艺术", "蒸汽朋克", "飞艇", "维多利亚"], model: "stable-diffusion" },
  { title: "圣洁天使降临场景", content: "concept art of a six-winged seraph descending from heaven, golden light rays, clouds parting, intricate feathered wings, divine atmosphere, baroque, highly detailed", contentZh: "概念艺术，六翼炽天使从天而降，金色光柱，云层分开，繁复羽翼，神圣氛围，巴洛克风格，超精细", tags: ["概念艺术", "天使", "神圣", "巴洛克"], model: "dall-e-3" },
  { title: "机械巨兽攻城场景", content: "massive mechanical war beast attacking a fortress, soldiers fleeing, smoke and fire, epic battle, dramatic lighting, dark fantasy concept art --ar 21:9 --v 6 --stylize 500", contentZh: "巨型机械战争巨兽攻城，士兵溃逃，烟火弥漫，史诗战役，戏剧化光影，暗黑奇幻概念艺术", tags: ["概念艺术", "机械", "战役", "史诗"], model: "midjourney" },
  { title: "水下亚特兰蒂斯遗迹", content: "concept art of sunken atlantis ruins, coral covered columns, shafts of light, schools of fish, ancient statues, deep blue, mysterious, detailed matte painting", contentZh: "沉没亚特兰蒂斯遗迹概念艺术，覆珊瑚石柱，光柱，鱼群，古老雕像，深蓝调，神秘，精细哑光绘画", tags: ["概念艺术", "亚特兰蒂斯", "水下", "遗迹"], model: "flux" },
  // ===== 产品摄影 41-50 =====
  { title: "奢华香水广告摄影", content: "luxury perfume bottle on reflective black surface, golden petals swirling, soft backlight, water splash, macro product shot, premium branding, cinematic --ar 4:5 --v 6 --stylize 300", contentZh: "奢华香水瓶置于反光黑色台面，金色花瓣环绕，柔背光，水花飞溅，微距产品拍摄，高端品牌感，电影感", tags: ["产品摄影", "香水", "商业", "高端"], model: "midjourney" },
  { title: "运动鞋广告特写", content: "premium running sneaker floating, dynamic splashes of colored powder, studio lighting, sharp detail, vibrant gradient background, commercial product photography, 8k", contentZh: "高端跑鞋悬浮，彩色粉末动态飞溅，影棚灯光，锐利细节，鲜艳渐变背景，商业产品摄影，8K", tags: ["产品摄影", "运动鞋", "商业", "动感"], model: "flux" },
  { title: "机械腕表微距", content: "macro product photo of luxury mechanical watch, exposed gears, sapphire crystal, dramatic side light, dark background, water droplets, ultra sharp, commercial, 8k", contentZh: "奢华机械腕表微距产品照，裸露齿轮，蓝宝石镜面，戏剧化侧光，暗色背景，水珠，超锐利，商业，8K", tags: ["产品摄影", "腕表", "微距", "商业"], model: "stable-diffusion" },
  { title: "手工咖啡杯静物", content: "artisan ceramic coffee cup on wooden table, latte art, steam rising, scattered beans, soft morning window light, cozy cafe atmosphere, product still life, ultra detailed", contentZh: "手工陶瓷咖啡杯置于木桌，拉花，热气升腾，散落咖啡豆，柔和晨光窗光，温馨咖啡馆氛围，产品静物，超精细", tags: ["产品摄影", "咖啡", "静物", "温馨"], model: "dall-e-3" },
  { title: "智能手机广告渲染", content: "sleek smartphone floating with vibrant abstract wallpaper, glossy glass back, studio reflections, clean gradient background, apple style product render, 8k --ar 1:1 --v 6", contentZh: "流线智能手机悬浮，鲜艳抽象壁纸，光亮玻璃背板，影棚反射，干净渐变背景，苹果风格产品渲染，8K", tags: ["产品摄影", "手机", "渲染", "科技"], model: "midjourney" },
  { title: "高端化妆品组合", content: "luxury skincare set on marble podium, soft silk fabric, dewy droplets, golden hour light, minimal elegant, cosmetic advertising, commercial photography, 8k", contentZh: "高端护肤套装置于大理石台座，柔软丝绸，水珠，黄金时刻光线，极简优雅，化妆品广告，商业摄影，8K", tags: ["产品摄影", "化妆品", "高端", "极简"], model: "flux" },
  { title: "威士忌酒瓶氛围摄影", content: "whisky bottle beside crystal glass with ice, warm amber glow, smoky atmosphere, dark moody bar background, rim light, luxury spirits advertising, ultra detailed", contentZh: "威士忌酒瓶旁水晶杯加冰，温暖琥珀光，烟雾氛围，暗调酒吧背景，轮廓光，高端烈酒广告，超精细", tags: ["产品摄影", "威士忌", "氛围", "高端"], model: "stable-diffusion" },
  { title: "手作甜品摆盘", content: "artisan french pastry on ceramic plate, berry sauce swirl, mint garnish, powdered sugar, soft natural light, michelin plating, top down, food magazine quality", contentZh: "手作法式甜点置于陶瓷盘，莓果酱漩涡，薄荷点缀，糖粉，柔和自然光，米其林摆盘，俯拍，美食杂志品质", tags: ["产品摄影", "甜品", "摆盘", "美食"], model: "dall-e-3" },
  { title: "耳机悬浮广告", content: "premium over-ear headphones floating, sound wave light trails, matte black and rose gold, dark studio, dramatic rim light, commercial product render --ar 1:1 --v 6", contentZh: "高端头戴式耳机悬浮，声波光轨，哑光黑与玫瑰金，暗色影棚，戏剧化轮廓光，商业产品渲染", tags: ["产品摄影", "耳机", "渲染", "科技"], model: "midjourney" },
  { title: "珠宝戒指特写", content: "diamond engagement ring macro, sparkling facets, velvet box, soft spot light, bokeh background, luxury jewelry advertising, ultra sharp, 8k product shot", contentZh: "钻戒微距，闪耀切面，丝绒盒，柔聚光灯，散景背景，高端珠宝广告，超锐利，8K 产品拍摄", tags: ["产品摄影", "珠宝", "微距", "高端"], model: "flux" },
  // ===== Logo设计 51-60 =====
  { title: "极简线条飞鸟 Logo", content: "minimalist logo design for a tech startup, single continuous golden ratio line forming an abstract bird, monochrome, vector, flat, professional, white background --ar 1:1 --v 6 --stylize 200", contentZh: "科技初创公司极简 Logo 设计，单一连续黄金比例线条构成抽象飞鸟，单色，矢量，扁平，专业，白底", tags: ["Logo", "极简", "线条", "矢量"], model: "midjourney" },
  { title: "咖啡店徽章 Logo", content: "vintage badge logo for a coffee shop, coffee cup with steam, laurel wreath, retro typography placeholder, warm brown tones, flat vector style, clean, professional", contentZh: "咖啡馆复古徽章 Logo，冒热气的咖啡杯，桂冠环饰，复古字体占位，温暖棕色调，扁平矢量风格，干净专业", tags: ["Logo", "徽章", "复古", "咖啡"], model: "dall-e-3" },
  { title: "科技几何渐变 Logo", content: "modern tech company logo, abstract geometric shape, blue purple gradient, 3d glossy, minimal, futuristic, on dark background, professional brand identity", contentZh: "现代科技公司 Logo，抽象几何形，蓝紫渐变，3D 光泽，极简，未来感，深色背景，专业品牌识别", tags: ["Logo", "几何", "渐变", "科技"], model: "flux" },
  { title: "宠物店手绘 Logo", content: "hand drawn logo for a pet shop, cute dog and cat silhouette, playful, warm colors, flat illustration, circle emblem, friendly, professional vector", contentZh: "宠物店手绘 Logo，可爱的狗与猫剪影，活泼，暖色调，扁平插画，圆形徽章，亲切，专业矢量", tags: ["Logo", "手绘", "宠物", "可爱"], model: "stable-diffusion" },
  { title: "健身品牌猛兽 Logo", content: "bold logo for a fitness brand, stylized lion head, aggressive, gold and black, sharp angles, strong, emblem style, vector, white background --ar 1:1 --v 6", contentZh: "健身品牌醒目 Logo，风格化狮头，凶猛，金黑配色，锐利角度，力量感，徽章风格，矢量，白底", tags: ["Logo", "健身", "猛兽", "徽章"], model: "midjourney" },
  { title: "环保品牌树叶 Logo", content: "eco brand logo, leaf and water drop forming infinity symbol, green and blue, clean flat vector, minimal, modern, sustainability theme, white background", contentZh: "环保品牌 Logo，树叶与水滴构成无限符号，绿蓝配色，干净扁平矢量，极简，现代，可持续主题，白底", tags: ["Logo", "环保", "极简", "矢量"], model: "dall-e-3" },
  { title: "游戏战队电竞 Logo", content: "esports team logo, fierce wolf mascot, sharp geometric, neon cyan and magenta, dynamic, shield emblem, gaming style, vector, dark background", contentZh: "电竞战队 Logo，凶猛狼形吉祥物，锐利几何，霓虹青与品红，动感，盾形徽章，游戏风格，矢量，深色背景", tags: ["Logo", "电竞", "狼", "霓虹"], model: "flux" },
  { title: "烘焙坊手作 Logo", content: "artisan bakery logo, wheat sheaf and rolling pin, hand drawn rustic style, warm cream and brown, circle stamp, vintage, professional branding", contentZh: "手作烘焙坊 Logo，麦穗与擀面杖，手绘质朴风格，温暖奶油棕，圆形印章，复古，专业品牌", tags: ["Logo", "烘焙", "手绘", "复古"], model: "stable-diffusion" },
  { title: "美妆品牌优雅 Logo", content: "elegant beauty brand logo, abstract lotus and woman profile, gold foil, thin lines, luxurious, minimal, on blush pink background --ar 1:1 --v 6 --stylize 250", contentZh: "优雅美妆品牌 Logo，抽象莲花与女性侧脸，金箔，细线条，奢华，极简，浅粉背景", tags: ["Logo", "美妆", "优雅", "奢华"], model: "midjourney" },
  { title: "音乐应用抽象 Logo", content: "music app logo, abstract sound wave forming a play button, vibrant gradient, modern flat, minimal, app icon style, clean, professional", contentZh: "音乐应用 Logo，抽象声波构成播放按钮，鲜艳渐变，现代扁平，极简，应用图标风格，干净专业", tags: ["Logo", "音乐", "抽象", "应用图标"], model: "dall-e-3" },
  // ===== UI设计 61-70 =====
  { title: "金融 App 仪表盘 UI", content: "modern fintech app dashboard ui, clean cards, data charts, dark mode, purple accent, glassmorphism, minimal, dribbble style, high fidelity --ar 9:16 --v 6", contentZh: "现代金融应用仪表盘 UI，干净卡片，数据图表，深色模式，紫色点缀，玻璃拟态，极简，Dribbble 风格，高保真", tags: ["UI设计", "仪表盘", "金融", "深色"], model: "midjourney" },
  { title: "外卖订餐 App 界面", content: "food delivery app home screen ui, appetizing food photos, vibrant orange theme, bottom nav, search bar, clean cards, modern, high fidelity mockup", contentZh: "外卖应用首页 UI，诱人美食图，鲜艳橙色主题，底部导航，搜索栏，干净卡片，现代，高保真原型", tags: ["UI设计", "外卖", "App", "橙色"], model: "flux" },
  { title: "健身追踪 Dashboard", content: "fitness tracking dashboard ui, rings and charts, activity stats, dark theme with neon green, clean typography, glassmorphism, modern, dribbble style", contentZh: "健身追踪仪表盘 UI，圆环与图表，活动数据，深色主题配霓虹绿，干净字体，玻璃拟态，现代，Dribbble 风格", tags: ["UI设计", "健身", "数据", "深色"], model: "dall-e-3" },
  { title: "音乐播放器极简 UI", content: "minimal music player ui, album art, progress bar, soft gradient background, rounded controls, pastel colors, clean, modern, high fidelity", contentZh: "极简音乐播放器 UI，专辑封面，进度条，柔和渐变背景，圆角控件，粉彩配色，干净现代，高保真", tags: ["UI设计", "音乐", "极简", "粉彩"], model: "stable-diffusion" },
  { title: "旅行预订网站 Landing", content: "travel booking landing page ui, hero image of tropical beach, search box, cards, clean layout, modern sans serif, blue and white, professional --ar 16:9 --v 6", contentZh: "旅行预订网站着陆页 UI，热带海滩主视觉，搜索框，卡片，干净布局，现代无衬线字体，蓝白配色，专业", tags: ["UI设计", "着陆页", "旅行", "蓝白"], model: "midjourney" },
  { title: "加密钱包深色 UI", content: "crypto wallet app ui, portfolio chart, token list, dark mode, neon accents, glassmorphism cards, modern fintech, high fidelity, dribbble", contentZh: "加密钱包应用 UI，资产图表，代币列表，深色模式，霓虹点缀，玻璃拟态卡片，现代金融科技，高保真，Dribbble", tags: ["UI设计", "加密", "钱包", "深色"], model: "flux" },
  { title: "电商商品详情页", content: "ecommerce product detail page ui, large product image, color variants, add to cart, reviews, clean grid, modern, professional, high fidelity mockup", contentZh: "电商商品详情页 UI，大商品图，颜色选项，加入购物车，评价，干净网格，现代专业，高保真原型", tags: ["UI设计", "电商", "详情页", "现代"], model: "dall-e-3" },
  { title: "天气应用灵动岛 UI", content: "weather app ui, dynamic island, hourly forecast, animated clouds, soft gradient sky background, clean, minimal, modern, high fidelity", contentZh: "天气应用 UI，灵动岛，逐时预报，动画云朵，柔和渐变天空背景，干净极简现代，高保真", tags: ["UI设计", "天气", "极简", "渐变"], model: "stable-diffusion" },
  { title: "冥想 App 治愈 UI", content: "meditation app ui, calm gradient background, breathing animation circle, soft pastel, rounded cards, serene, minimal, modern wellness --ar 9:16 --v 6", contentZh: "冥想应用 UI，平静渐变背景，呼吸动画圆环，柔和粉彩，圆角卡片，宁静极简，现代健康", tags: ["UI设计", "冥想", "治愈", "粉彩"], model: "midjourney" },
  { title: "SaaS 后台数据看板", content: "saas analytics dashboard ui, multiple charts, sidebar nav, kpi cards, clean light theme, blue accent, modern, professional, high fidelity", contentZh: "SaaS 数据分析后台 UI，多图表，侧边导航，KPI 卡片，干净浅色主题，蓝色点缀，现代专业，高保真", tags: ["UI设计", "后台", "数据", "SaaS"], model: "flux" },
  // ===== 建筑 71-80 =====
  { title: "黄昏野兽派未来建筑", content: "futuristic brutalist architecture, massive concrete forms, golden hour sunset, dramatic long shadows, wide angle, architectural photography, leica, ultra sharp --ar 16:9 --v 6 --stylize 300", contentZh: "未来野兽派建筑，巨大混凝土体块，黄金时刻落日，戏剧化长阴影，广角，建筑摄影，徕卡，超锐利", tags: ["建筑", "野兽派", "黄昏", "摄影"], model: "midjourney" },
  { title: "现代极简别墅外观", content: "modern minimalist villa exterior, cantilevered concrete and glass, infinity pool, lush garden, warm interior light at dusk, architectural photography, 8k", contentZh: "现代极简别墅外观，悬挑混凝土与玻璃，无边泳池，葱郁花园，黄昏温暖室内光，建筑摄影，8K", tags: ["建筑", "别墅", "极简", "现代"], model: "flux" },
  { title: "中式庭院园林", content: "traditional chinese courtyard garden, white walls grey tiles, koi pond, moon gate, bamboo, misty morning, ink painting atmosphere, serene, architectural", contentZh: "传统中式庭院园林，白墙灰瓦，锦鲤池，月洞门，竹林，晨雾弥漫，水墨意境，宁静，建筑", tags: ["建筑", "中式", "庭院", "园林"], model: "stable-diffusion" },
  { title: "未来生态摩天楼", content: "futuristic eco skyscraper covered in vertical gardens, cascading terraces, solar panels, flying vehicles, blue sky, sustainable architecture concept, highly detailed", contentZh: "未来生态摩天楼，覆垂直花园，层叠露台，太阳能板，飞行载具，蓝天，可持续建筑概念，超精细", tags: ["建筑", "未来", "生态", "摩天楼"], model: "dall-e-3" },
  { title: "北欧极简室内客厅", content: "scandinavian minimalist living room interior, large window natural light, concrete and oak, single fiddle leaf fig, neutral palette, architectural digest, 8k --ar 16:9 --v 6", contentZh: "北欧极简客厅室内，大窗自然光，混凝土与橡木，单株琴叶榕，中性色调，安邸 AD 风格，8K", tags: ["建筑", "室内", "北欧", "极简"], model: "midjourney" },
  { title: "玻璃幕墙办公大堂", content: "modern corporate lobby, double height glass curtain wall, travertine floor, minimal reception desk, indoor trees, soft daylight, architectural photography, 8k", contentZh: "现代企业大堂，双层挑高玻璃幕墙，洞石地面，极简前台，室内树木，柔和天光，建筑摄影，8K", tags: ["建筑", "大堂", "玻璃", "现代"], model: "flux" },
  { title: "日式禅意茶室", content: "japanese zen tea room interior, tatami, shoji screens, tokonoma alcove, ikebana, soft diffused light, minimal, wabi sabi, architectural, serene", contentZh: "日式禅意茶室室内，榻榻米，障子屏风，床之间凹龛，池坊插花，柔和漫射光，极简侘寂，建筑，宁静", tags: ["建筑", "茶室", "日式", "禅意"], model: "stable-diffusion" },
  { title: "沙漠土著夯土建筑", content: "sustainable rammed earth house in desert, organic curves, thermal mass, shaded courtyard, palm trees, golden hour, vernacular architecture, ultra detailed", contentZh: "沙漠中可持续夯土住宅，有机曲线，蓄热墙体，遮阴庭院，棕榈树，黄金时刻，乡土建筑，超精细", tags: ["建筑", "夯土", "沙漠", "可持续"], model: "dall-e-3" },
  { title: "哥特教堂彩窗光影", content: "gothic cathedral interior, towering ribbed vaults, stained glass casting colorful light, sunbeams, stone pillars, atmospheric, cinematic, ultra detailed --ar 4:5 --v 6", contentZh: "哥特教堂室内，高耸肋拱，彩色玻璃投下斑斓光影，光柱，石柱，氛围感，电影感，超精细", tags: ["建筑", "哥特", "教堂", "光影"], model: "midjourney" },
  { title: "山巅悬崖玻璃屋", content: "glass cabin perched on mountain cliff, panoramic valley view, sunset reflection, minimalist, dramatic, architectural visualization, ultra realistic, 8k", contentZh: "山巅悬崖玻璃小屋，全景山谷视野，落日反射，极简，戏剧化，建筑可视化，超写实，8K", tags: ["建筑", "玻璃屋", "悬崖", "山景"], model: "flux" },
  // ===== 美食 81-90 =====
  { title: "拉面商业美食摄影", content: "professional food photography, gourmet ramen bowl, steam rising, arranged toppings, chopsticks lifting noodles, dark moody background, side light, shallow dof --ar 4:5 --v 6 --stylize 300", contentZh: "专业美食摄影，豪华拉面碗，热气升腾，配料整齐，筷子挑起面条，暗调氛围背景，侧光，浅景深", tags: ["美食", "拉面", "商业", "摄影"], model: "midjourney" },
  { title: "汉堡广告特写", content: "juicy gourmet burger, melted cheese drip, fresh vegetables, sesame brioche bun, dynamic sauce splash, dark background, dramatic light, commercial food photography, 8k", contentZh: "多汁豪华汉堡，融化奶酪滴落，新鲜蔬菜，芝麻布里欧修包，动态酱汁飞溅，暗色背景，戏剧化光线，商业美食摄影，8K", tags: ["美食", "汉堡", "商业", "动感"], model: "flux" },
  { title: "寿司拼盘顶视角", content: "top down flat lay of premium sushi platter, fresh salmon tuna, garnish, slate board, wasabi, soft natural light, michelin presentation, ultra detailed, 8k", contentZh: "顶级寿司拼盘顶视角平铺，新鲜三文鱼金枪鱼，配菜，石板，芥末，柔和自然光，米其林摆盘，超精细，8K", tags: ["美食", "寿司", "俯拍", "日式"], model: "stable-diffusion" },
  { title: "草莓奶油蛋糕", content: "strawberry cream layer cake on marble table, fresh berries, powdered sugar, soft window light, cream drips, bakery advertising, mouthwatering, ultra detailed", contentZh: "草莓奶油蛋糕置于大理石桌，新鲜莓果，糖粉，柔和窗光，奶油滴落，烘焙广告，令人垂涎，超精细", tags: ["美食", "蛋糕", "草莓", "烘焙"], model: "dall-e-3" },
  { title: "牛排炉火烧烤", content: "grilled ribeye steak, grill marks, rosemary, garlic butter melting, cast iron skillet, flames, dark rustic background, dramatic, food photography --ar 4:5 --v 6", contentZh: "炭烤肉眼牛排，焦痕，迷迭香，融化蒜香黄油，铸铁锅，火焰，暗色乡村背景，戏剧化，美食摄影", tags: ["美食", "牛排", "烧烤", "氛围"], model: "midjourney" },
  { title: "马卡龙粉彩静物", content: "assorted french macarons on tiered stand, pastel colors, soft pink background, delicate, dreamy light, patisserie advertising, ultra detailed, 8k", contentZh: "法式马卡龙置于层架，粉彩配色，柔粉背景，精致，梦幻光线，法式甜品广告，超精细，8K", tags: ["美食", "马卡龙", "粉彩", "法式"], model: "flux" },
  { title: "热咖啡拿铁拉花", content: "latte art coffee in ceramic cup, heart pattern, steam, scattered beans, wooden cafe table, warm morning light, cozy, food photography, ultra detailed", contentZh: "陶瓷杯拿铁拉花，心形图案，热气，散落咖啡豆，木质咖啡馆桌，温暖晨光，温馨，美食摄影，超精细", tags: ["美食", "咖啡", "拉花", "温馨"], model: "stable-diffusion" },
  { title: "缤纷水果拼盘", content: "colorful tropical fruit platter, mango, dragon fruit, kiwi, berries, mint, on rustic wood, bright natural light, fresh and vibrant, food photography", contentZh: "缤纷热带水果拼盘，芒果、火龙果、奇异果、莓果、薄荷，置于质朴木板，明亮自然光，新鲜鲜艳，美食摄影", tags: ["美食", "水果", "清新", "热带"], model: "dall-e-3" },
  { title: "火锅沸腾麻辣", content: "sizzling chinese hot pot, red chili oil, boiling broth, fresh ingredients, steam, chopsticks, dark moody restaurant, dramatic light --ar 4:5 --v 6 --stylize 300", contentZh: "沸腾中式火锅，红油辣椒，沸腾汤底，新鲜食材，热气，筷子，暗调餐厅，戏剧化光线", tags: ["美食", "火锅", "中餐", "氛围"], model: "midjourney" },
  { title: "巧克力熔岩蛋糕", content: "molten chocolate lava cake, flowing chocolate center, dusted cocoa, vanilla ice cream, raspberry, dark moody background, warm light, dessert advertising, 8k", contentZh: "巧克力熔岩蛋糕，流心巧克力，撒可可粉，香草冰淇淋，覆盆子，暗调背景，暖光，甜品广告，8K", tags: ["美食", "巧克力", "甜品", "熔岩"], model: "flux" },
  // ===== 动物 91-100 =====
  { title: "雪地雄鹰展翅", content: "majestic bald eagle spreading wings in snowy mountain, sharp eyes, detailed feathers, golden hour rim light, wildlife photography, national geographic --ar 3:2 --v 6 --stylize 300", contentZh: "雄伟白头海雕在雪山展翅，锐利眼神，细致羽毛，黄金时刻轮廓光，野生动物摄影，国家地理", tags: ["动物", "鹰", "野生动物", "摄影"], model: "midjourney" },
  { title: "水下座头鲸", content: "humpback whale gliding through sunlit blue ocean, god rays piercing water, small fish school, majestic scale, underwater photography, national geographic, 8k", contentZh: "座头鲸游过阳光蓝色海洋，光柱穿透水面，小鱼群，雄伟尺度，水下摄影，国家地理，8K", tags: ["动物", "鲸鱼", "水下", "海洋"], model: "flux" },
  { title: "萌宠猫咪特写", content: "1cat, maine coon, fluffy fur, green eyes, sitting by window, soft sunlight, bokeh, ultra detailed, photography, cute, best quality", contentZh: "1cat，缅因猫，蓬松毛发，绿眼睛，窗边坐着，柔和阳光，散景，超精细，摄影，可爱，最佳品质", tags: ["动物", "猫", "萌宠", "特写"], model: "stable-diffusion" },
  { title: "非洲草原狮群", content: "lion pride resting under acacia tree at sunset, golden savanna, dramatic sky, wildlife photography, national geographic style, ultra detailed, cinematic", contentZh: "狮群在夕阳下金合欢树下休憩，金色草原，戏剧化天空，野生动物摄影，国家地理风格，超精细，电影感", tags: ["动物", "狮子", "草原", "夕阳"], model: "dall-e-3" },
  { title: "北极熊冰原独行", content: "lone polar bear walking on drifting ice floe, arctic sunset, reflections, vast empty landscape, climate change mood, wildlife photography --ar 16:9 --v 6", contentZh: "孤独北极熊行走在浮冰上，北极落日，倒影，辽阔空旷景观，气候变化氛围，野生动物摄影", tags: ["动物", "北极熊", "冰原", "环保"], model: "midjourney" },
  { title: "森林红狐雪地", content: "red fox in snowy forest, alert pose, detailed fur with snowflakes, soft winter light, bokeh background, wildlife photography, ultra realistic, 8k", contentZh: "雪林中的红狐，警觉姿态，细致毛发沾雪花，柔和冬日光线，散景背景，野生动物摄影，超写实，8K", tags: ["动物", "狐狸", "雪景", "森林"], model: "flux" },
  { title: "热带金刚鹦鹉", content: "vibrant scarlet macaw parrot perched on branch, rainforest background, detailed feathers, bright tropical light, wildlife photography, ultra detailed, best quality", contentZh: "鲜艳绯红金刚鹦鹉栖于枝头，雨林背景，细致羽毛，明亮热带光线，野生动物摄影，超精细，最佳品质", tags: ["动物", "鹦鹉", "热带", "雨林"], model: "stable-diffusion" },
  { title: "大象家族迁徙", content: "herd of elephants walking across dusty african plain at sunset, silhouettes, dramatic sky, family bond, wildlife photography, national geographic, cinematic", contentZh: "象群夕阳下行走在尘土飞扬的非洲平原，剪影，戏剧化天空，家族羁绊，野生动物摄影，国家地理，电影感", tags: ["动物", "大象", "迁徙", "非洲"], model: "dall-e-3" },
  { title: "海豚跃出水面", content: "dolphin leaping out of turquoise ocean, water droplets, sunny sky, dynamic motion, tropical, wildlife photography, freeze frame --ar 16:9 --v 6 --stylize 300", contentZh: "海豚跃出碧绿海面，水珠飞溅，晴朗天空，动态瞬间，热带，野生动物摄影，定格", tags: ["动物", "海豚", "海洋", "动态"], model: "midjourney" },
  { title: "雨林树懒慵懒", content: "sloths hanging on rainforest branch, detailed fur, moss, soft dappled light, slow motion mood, wildlife photography, ultra realistic, 8k", contentZh: "树懒悬挂于雨林枝头，细致毛发，苔藓，柔和斑驳光线，慢生活氛围，野生动物摄影，超写实，8K", tags: ["动物", "树懒", "雨林", "慵懒"], model: "flux" },
  // ===== 科幻 101-110 =====
  { title: "火星殖民地穹顶", content: "mars colony under transparent domes, red desert, solar panels, rockets, two moons, dust storm, cinematic sci-fi, retrofuturistic, ultra detailed --ar 16:9 --v 6 --stylize 500", contentZh: "透明穹顶下的火星殖民地，红色沙漠，太阳能板，火箭，两轮月亮，沙尘暴，电影感科幻，复古未来，超精细", tags: ["科幻", "火星", "殖民地", "未来"], model: "midjourney" },
  { title: "巨型星际飞船船坞", content: "gigantic starship under construction in orbital shipyard, sparks, astronauts, earth below, sci-fi concept art, cinematic scale, ultra detailed, 8k", contentZh: "轨道船坞中建造的巨型星际飞船，火花，宇航员，下方地球，科幻概念艺术，史诗尺度，超精细，8K", tags: ["科幻", "飞船", "太空", "未来"], model: "flux" },
  { title: "赛博仿生人特写", content: "cyborg android face close up, exposed mechanical parts under synthetic skin, glowing blue eyes, circuit patterns, studio rim light, hyperrealistic, cyberpunk, 8k", contentZh: "赛博仿生人面部特写，合成皮肤下裸露机械部件，发光蓝眼，电路纹路，影棚轮廓光，超写实，赛博朋克，8K", tags: ["科幻", "仿生人", "赛博", "特写"], model: "stable-diffusion" },
  { title: "外星异形生物", content: "alien creature concept, bioluminescent tentacles, multiple eyes, alien jungle, eerie atmosphere, science fiction creature design, highly detailed, cinematic", contentZh: "外星生物概念，生物发光触手，多眼，外星丛林，诡异氛围，科幻生物设计，超精细，电影感", tags: ["科幻", "外星", "异形", "生物"], model: "dall-e-3" },
  { title: "未来东京天际线", content: "futuristic tokyo skyline at night, flying cars, holographic billboards, mega skyscrapers, neon reflections, blade runner aesthetic, cinematic --ar 21:9 --v 6 --stylize 500", contentZh: "未来东京夜景天际线，飞行汽车，全息广告牌，巨型摩天楼，霓虹倒影，银翼杀手美学，电影感", tags: ["科幻", "东京", "未来", "赛博朋克"], model: "midjourney" },
  { title: "空间站内部走廊", content: "interior of rotating space station, curved corridor, panoramic windows showing earth, white minimal design, soft led lighting, sci-fi, ultra realistic, 8k", contentZh: "旋转空间站内部，弧形走廊，全景舷窗可见地球，白色极简设计，柔和 LED 灯光，科幻，超写实，8K", tags: ["科幻", "空间站", "太空", "极简"], model: "flux" },
  { title: "机甲战士战斗", content: "giant mecha robot in city battle, explosions, smoke, dynamic pose, detailed mechanical design, cyberpunk, cinematic lighting, masterpiece, ultra detailed", contentZh: "巨型机甲城市战斗，爆炸，烟雾，动态姿势，精细机械设计，赛博朋克，电影感光影，杰作，超精细", tags: ["科幻", "机甲", "战斗", "城市"], model: "stable-diffusion" },
  { title: "时间旅行虫洞", content: "wormhole portal swirling with cosmic colors, spaceship entering, stars and galaxies bending, sci-fi concept art, vibrant, cinematic, highly detailed", contentZh: "虫洞门户旋转宇宙色彩，飞船驶入，恒星与星系弯曲，科幻概念艺术，鲜艳，电影感，超精细", tags: ["科幻", "虫洞", "宇宙", "飞船"], model: "dall-e-3" },
  { title: "废土后启示录城市", content: "post-apocalyptic ruined city, overgrown skyscrapers, abandoned cars, lone survivor, dramatic sunset, fallout aesthetic, cinematic --ar 16:9 --v 6 --stylize 400", contentZh: "末日废墟城市，蔓延的摩天楼，废弃汽车，孤独幸存者，戏剧化落日，辐射美学，电影感", tags: ["科幻", "废土", "末日", "城市"], model: "midjourney" },
  { title: "AI 意识数据流", content: "abstract representation of ai consciousness, flowing data streams, glowing nodes, neural network, dark background, sci-fi visualization, ultra detailed, 8k", contentZh: "AI 意识抽象表现，流动数据流，发光节点，神经网络，深色背景，科幻可视化，超精细，8K", tags: ["科幻", "AI", "抽象", "数据"], model: "flux" },
  // ===== 奇幻 111-120 =====
  { title: "悬浮天空岛屿", content: "epic fantasy floating islands above clouds, cascading waterfalls into void, aurora sky, ancient ruins, golden hour rim light, matte painting, 8k --ar 16:9 --v 6 --stylize 400", contentZh: "史诗奇幻悬浮岛屿在云海之上，瀑布泻入虚空，极光天空，古老遗迹，黄金时刻轮廓光，哑光绘画，8K", tags: ["奇幻", "悬浮岛", "史诗", "风景"], model: "midjourney" },
  { title: "精灵森林神殿", content: "elven forest sanctuary, ancient carved stone temple, bioluminescent plants, soft god rays, mystical atmosphere, fantasy concept art, ultra detailed, 8k", contentZh: "精灵森林圣所，古老雕刻石殿，生物发光植物，柔和光柱，神秘氛围，奇幻概念艺术，超精细，8K", tags: ["奇幻", "精灵", "森林", "神殿"], model: "flux" },
  { title: "巫师塔楼之夜", content: "wizard tower on cliff, glowing magical windows, stormy sky, lightning, flying owls, dark fantasy, detailed matte painting, artstation, masterpiece", contentZh: "悬崖上的巫师塔，发光魔法窗，风暴天空，闪电，飞翔猫头鹰，暗黑奇幻，精细哑光绘画，ArtStation，杰作", tags: ["奇幻", "巫师", "塔楼", "暗黑"], model: "stable-diffusion" },
  { title: "龙骑士空中激战", content: "dragon rider battling in stormy sky, armored knight on red dragon, lightning, epic scale, dynamic, fantasy concept art, cinematic, highly detailed", contentZh: "龙骑士风暴天空激战，铠甲骑士骑红龙，闪电，史诗尺度，动感，奇幻概念艺术，电影感，超精细", tags: ["奇幻", "龙骑士", "激战", "史诗"], model: "dall-e-3" },
  { title: "魔法图书馆", content: "endless magical library, floating books, glowing runes, spiral staircases, shafts of light, dust motes, fantasy, intricate, cinematic --ar 16:9 --v 6 --stylize 500", contentZh: "无尽魔法图书馆，悬浮书籍，发光符文，旋转楼梯，光柱，尘埃微粒，奇幻，繁复，电影感", tags: ["奇幻", "图书馆", "魔法", "史诗"], model: "midjourney" },
  { title: "美人鱼海底王国", content: "mermaid kingdom underwater, coral palace, glowing pearls, fish, shafts of light, fantasy, ethereal, ultra detailed, 8k concept art", contentZh: "水下美人鱼王国，珊瑚宫殿，发光珍珠，鱼群，光柱，奇幻，空灵，超精细，8K 概念艺术", tags: ["奇幻", "美人鱼", "海底", "王国"], model: "flux" },
  { title: "兽人部落篝火", content: "orc tribe around bonfire at night, tribal tattoos, fur armor, rugged, dramatic firelight, dark fantasy, concept art, detailed, artstation", contentZh: "夜晚围篝火的兽人部落，部落纹身，皮毛铠甲，粗犷，戏剧化火光，暗黑奇幻，概念艺术，精细，ArtStation", tags: ["奇幻", "兽人", "部落", "暗黑"], model: "stable-diffusion" },
  { title: "独角兽森林漫步", content: "white unicorn walking through enchanted forest, glowing flowers, fireflies, sun rays, magical atmosphere, fantasy, ethereal, highly detailed, dreamy", contentZh: "白色独角兽穿行魔法森林，发光花朵，萤火虫，阳光，魔法氛围，奇幻，空灵，超精细，梦幻", tags: ["奇幻", "独角兽", "森林", "魔法"], model: "dall-e-3" },
  { title: "矮人地下锻造城", content: "dwarven underground forge city, molten lava rivers, massive anvils, ornate stone architecture, glowing embers, epic fantasy, cinematic --ar 16:9 --v 6 --stylize 500", contentZh: "矮人地下锻造城，熔岩河流，巨型铁砧，华丽石质建筑，发光余烬，史诗奇幻，电影感", tags: ["奇幻", "矮人", "锻造", "地下"], model: "midjourney" },
  { title: "仙界云中宫殿", content: "celestial palace above clouds, golden rooftops, cranes flying, peach blossom, xianxia aesthetic, ethereal light, fantasy, ultra detailed, 8k", contentZh: "云中仙界宫殿，金色屋顶，仙鹤飞翔，桃花，仙侠美学，空灵光线，奇幻，超精细，8K", tags: ["奇幻", "仙侠", "宫殿", "云海"], model: "flux" },
  // ===== 赛博朋克 121-130 =====
  { title: "赛博街头夜市", content: "cyberpunk street market at night, neon signs in japanese, rain reflections, holographic ads, cyborg vendors, blade runner aesthetic, teal orange --ar 21:9 --v 6 --stylize 400", contentZh: "赛博朋克夜市，日文霓虹招牌，雨水倒影，全息广告，机械义体摊贩，银翼杀手美学，青橙色调", tags: ["赛博朋克", "夜市", "霓虹", "街头"], model: "midjourney" },
  { title: "霓虹女黑客肖像", content: "cyberpunk female hacker portrait, neon pink and cyan lighting, augmented reality visor, cable hair, dark room with screens, ultra detailed, cinematic, 8k", contentZh: "赛博朋克女黑客肖像，霓虹粉青光线，增强现实面罩，线缆头发，布满屏幕的暗室，超精细，电影感，8K", tags: ["赛博朋克", "人像", "黑客", "霓虹"], model: "flux" },
  { title: "街头赛博少女", content: "1girl, cyberpunk streetwear, glowing tattoos, neon city background, rain, reflective puddles, cinematic lighting, ultra detailed, masterpiece, best quality", contentZh: "1girl，赛博朋克街头服饰，发光纹身，霓虹城市背景，雨水，反光水洼，电影感光影，超精细，杰作，最佳品质", tags: ["赛博朋克", "少女", "街头", "纹身"], model: "stable-diffusion" },
  { title: "未来飞行摩托", content: "futuristic flying motorcycle speeding through neon canyon city, motion blur, light trails, rain, cyberpunk, dynamic, cinematic, highly detailed", contentZh: "未来飞行摩托穿梭霓虹峡谷城市，运动模糊，光轨，雨水，赛博朋克，动感，电影感，超精细", tags: ["赛博朋克", "摩托", "未来", "动感"], model: "dall-e-3" },
  { title: "赛博诊所义体改造", content: "cyberpunk underground clinic, surgeon implanting cybernetic arm, dim lights, cables, patient, gritty, blade runner style, cinematic --ar 16:9 --v 6 --stylize 400", contentZh: "赛博朋克地下诊所，外科医生植入义体手臂，昏暗灯光，线缆，病人，粗粝，银翼杀手风格，电影感", tags: ["赛博朋克", "诊所", "义体", "暗黑"], model: "midjourney" },
  { title: "全息演唱偶像", content: "holographic idol performing on neon stage, crowd with glowing light sticks, futuristic concert, cyberpunk, dynamic, cinematic, ultra detailed, 8k", contentZh: "霓虹舞台上表演的全息偶像，挥舞荧光棒的观众，未来演唱会，赛博朋克，动感，电影感，超精细，8K", tags: ["赛博朋克", "偶像", "演唱会", "全息"], model: "flux" },
  { title: "赛博武士雨夜", content: "1boy, cyber samurai, glowing katana, neon rain, tokyo alley, reflective armor, dramatic lighting, cinematic, masterpiece, ultra detailed, best quality", contentZh: "1boy，赛博武士，发光武士刀，霓虹雨，东京小巷，反光铠甲，戏剧化光影，电影感，杰作，超精细，最佳品质", tags: ["赛博朋克", "武士", "雨夜", "刀"], model: "stable-diffusion" },
  { title: "巨型全息广告牌", content: "giant holographic advertisement towering over crowded cyberpunk street, geisha face, neon colors, rain, flying cars, cinematic, highly detailed", contentZh: "巨大全息广告牌矗立于拥挤赛博朋克街道，艺伎面孔，霓虹色彩，雨水，飞行汽车，电影感，超精细", tags: ["赛博朋克", "全息", "广告", "街头"], model: "dall-e-3" },
  { title: "赛博办公室数据流", content: "cyberpunk corporate office, transparent screens with data streams, executive with neural interface, city skyline night, teal magenta, cinematic --ar 16:9 --v 6", contentZh: "赛博朋克企业办公室，透明屏幕数据流，神经接口高管，夜景城市天际线，青品红色调，电影感", tags: ["赛博朋克", "办公室", "数据", "未来"], model: "midjourney" },
  { title: "地下赛博格斗场", content: "underground cyberpunk fight club, cybernetic fighters, neon lights, smoke, cheering crowd, gritty, dynamic, cinematic, ultra detailed, 8k", contentZh: "地下赛博朋克格斗场，义体斗士，霓虹灯，烟雾，欢呼人群，粗粝，动感，电影感，超精细，8K", tags: ["赛博朋克", "格斗", "地下", "动感"], model: "flux" },
  // ===== 水彩 131-140 =====
  { title: "威尼斯运河水彩", content: "loose watercolor painting of venetian canal, wet on wet, bleeding colors, paper texture, impressionistic, soft morning light, traditional medium --ar 3:2 --v 6 --stylize 200", contentZh: "威尼斯运河松散水彩画，湿画法，晕染色彩，纸张纹理，印象派，柔和晨光，传统媒介", tags: ["水彩", "威尼斯", "印象派", "速写"], model: "midjourney" },
  { title: "山间小屋水彩风景", content: "watercolor landscape of cozy cabin in pine forest mountains, misty, soft washes, warm chimney smoke, traditional painting, serene, ultra detailed", contentZh: "松林山中温馨小屋水彩风景，雾气，柔和渲染，温暖炊烟，传统绘画，宁静，超精细", tags: ["水彩", "风景", "小屋", "森林"], model: "flux" },
  { title: "花卉水彩速写", content: "watercolor sketch of wildflowers in vase, loose brush strokes, soft pastel colors, paper texture, botanical illustration, traditional medium, delicate", contentZh: "瓶中野花水彩速写，松散笔触，柔和粉彩，纸张纹理，植物插画，传统媒介，精致", tags: ["水彩", "花卉", "植物", "速写"], model: "stable-diffusion" },
  { title: "巴黎街角咖啡馆水彩", content: "watercolor painting of parisian street cafe, awning, people, soft warm tones, loose impressionistic style, traditional medium, charming, detailed", contentZh: "巴黎街角咖啡馆水彩画，遮阳棚，行人，柔和暖色调，松散印象派风格，传统媒介，迷人，精细", tags: ["水彩", "巴黎", "咖啡馆", "印象派"], model: "dall-e-3" },
  { title: "海边灯塔水彩", content: "watercolor of lighthouse on rocky cliff, crashing waves, seagulls, moody sky, loose washes, traditional painting, atmospheric --ar 3:2 --v 6 --stylize 200", contentZh: "岩石悬崖灯塔水彩，拍岸海浪，海鸥，氛围天空，松散渲染，传统绘画，富有氛围", tags: ["水彩", "灯塔", "海景", "氛围"], model: "midjourney" },
  { title: "秋日公园水彩", content: "watercolor painting of autumn park, golden trees, path, bench, soft sunlight, loose impressionistic, warm palette, traditional medium, serene", contentZh: "秋日公园水彩画，金色树木，小径，长椅，柔和阳光，松散印象派，暖色调，传统媒介，宁静", tags: ["水彩", "秋色", "公园", "印象派"], model: "flux" },
  { title: "热带水果水彩插画", content: "watercolor illustration of tropical fruits, mango, pineapple, papaya, vibrant yet soft colors, botanical style, paper texture, fresh, detailed", contentZh: "热带水果水彩插画，芒果、菠萝、木瓜，鲜艳而柔和的色彩，植物学风格，纸张纹理，清新，精细", tags: ["水彩", "水果", "插画", "热带"], model: "stable-diffusion" },
  { title: "雪夜村庄水彩", content: "watercolor painting of snowy village at night, warm window lights, smoke, pine trees, soft blue tones, cozy, traditional medium, atmospheric", contentZh: "雪夜村庄水彩画，温暖窗光，炊烟，松树，柔和蓝色调，温馨，传统媒介，富有氛围", tags: ["水彩", "雪景", "村庄", "温馨"], model: "dall-e-3" },
  { title: "樱花季水彩风景", content: "watercolor of cherry blossom along river, petals falling, soft pink, bridge, impressionistic, traditional painting, serene --ar 3:2 --v 6 --stylize 200", contentZh: "河边樱花水彩画，飘落花瓣，柔和粉色，桥梁，印象派，传统绘画，宁静", tags: ["水彩", "樱花", "河流", "印象派"], model: "midjourney" },
  { title: "山间晨雾水彩", content: "watercolor painting of mountains in morning mist, layered ridges, soft gradients, traditional chinese influence, serene, atmospheric, ultra detailed", contentZh: "晨雾山峦水彩画，层叠山脊，柔和渐变，中式意境，宁静，富有氛围，超精细", tags: ["水彩", "山景", "晨雾", "意境"], model: "flux" },
  // ===== 油画 141-150 =====
  { title: "古典肖像油画", content: "classical oil portrait of noblewoman, rembrandt lighting, rich textures, baroque style, dark background, fine art, museum quality --ar 4:5 --v 6 --stylize 300", contentZh: "贵族女子古典油画肖像，伦勃朗光，丰富肌理，巴洛克风格，暗色背景，艺术，博物馆品质", tags: ["油画", "肖像", "古典", "巴洛克"], model: "midjourney" },
  { title: "印象派花园油画", content: "impressionist oil painting of garden in full bloom, monet style, visible brush strokes, vibrant colors, dappled light, fine art, detailed", contentZh: "盛放花园印象派油画，莫奈风格，可见笔触，鲜艳色彩，斑驳光影，艺术，精细", tags: ["油画", "印象派", "花园", "莫奈"], model: "flux" },
  { title: "风暴海景油画", content: "oil painting of stormy sea, crashing waves, dramatic clouds, lighthouse, romanticism style, thick impasto, fine art, masterpiece", contentZh: "风暴海景油画，拍岸巨浪，戏剧化云层，灯塔，浪漫主义风格，厚涂肌理，艺术，杰作", tags: ["油画", "海景", "风暴", "浪漫主义"], model: "stable-diffusion" },
  { title: "梵高风星空村庄", content: "van gogh inspired oil painting of starry night over village, swirling sky, vivid brush strokes, post impressionism, expressive, fine art", contentZh: "梵高风格村庄星空油画，旋转天空，生动笔触，后印象派，表现力强，艺术", tags: ["油画", "梵高", "星空", "后印象派"], model: "dall-e-3" },
  { title: "文艺复兴圣母像", content: "renaissance oil painting of madonna and child, halos, soft sfumato, leonardo style, gold leaf accents, fine art, museum quality --ar 3:4 --v 6 --stylize 400", contentZh: "文艺复兴圣母与圣子油画，光环，柔和晕涂法，达芬奇风格，金箔点缀，艺术，博物馆品质", tags: ["油画", "文艺复兴", "圣母", "古典"], model: "midjourney" },
  { title: "现代抽象油画", content: "abstract oil painting, bold color blocks, texture palette knife, geometric composition, modern art, expressive, gallery quality, detailed", contentZh: "现代抽象油画，大胆色块，调色刀肌理，几何构图，现代艺术，表现力强，画廊品质，精细", tags: ["油画", "抽象", "现代", "几何"], model: "flux" },
  { title: "秋日林间小径油画", content: "oil painting of autumn forest path, golden leaves, dappled light, impressionist brushwork, warm palette, fine art, detailed, masterpiece", contentZh: "秋日林间小径油画，金色落叶，斑驳光影，印象派笔触，暖色调，艺术，精细，杰作", tags: ["油画", "秋色", "森林", "印象派"], model: "stable-diffusion" },
  { title: "雪中猎人油画", content: "oil painting of hunters in snowy forest, bruegel style, muted palette, atmospheric, narrative, flemish renaissance, fine art, detailed", contentZh: "雪林猎人油画，勃鲁盖尔风格，低饱和色调，氛围感，叙事性，佛兰德斯文艺复兴，艺术，精细", tags: ["油画", "雪景", "猎人", "文艺复兴"], model: "dall-e-3" },
  { title: "静物花卉油画", content: "dutch golden age still life oil painting, flowers in vase, dramatic chiaroscuro, insects, rich textures, fine art, museum quality --ar 4:5 --v 6", contentZh: "荷兰黄金时代静物花卉油画，瓶花，戏剧化明暗对比，昆虫，丰富肌理，艺术，博物馆品质", tags: ["油画", "静物", "花卉", "古典"], model: "midjourney" },
  { title: "浪漫主义山景油画", content: "romantic oil painting of majestic mountain landscape, dramatic clouds, lone wanderer, caspar david friedrich style, sublime, fine art, detailed", contentZh: "浪漫主义雄伟山景油画，戏剧化云层，孤独漫游者，弗里德里希风格，崇高感，艺术，精细", tags: ["油画", "浪漫主义", "山景", "崇高"], model: "flux" },
  // ===== 3D渲染 151-160 =====
  { title: "液态铬合金抽象", content: "abstract liquid chrome sculpture, iridescent holographic surface, studio softbox lighting, seamless loop, octane render, hyperrealistic, dark background --ar 1:1 --v 6 --stylize 400", contentZh: "抽象液态铬合金雕塑，全息虹彩表面，影棚柔光箱照明，无缝循环，Octane 渲染，超写实，深色背景", tags: ["3D渲染", "抽象", "金属", "全息"], model: "midjourney" },
  { title: "皮克斯风可爱机器人", content: "cute 3d robot character with big expressive eyes, pastel palette, pixar style, soft global illumination, octane render, clean studio background, charming", contentZh: "大眼可爱 3D 机器人角色，粉彩配色，皮克斯风格，柔和全局光照，Octane 渲染，干净影棚背景，迷人", tags: ["3D渲染", "角色", "可爱", "皮克斯"], model: "flux" },
  { title: "等距微型城市", content: "isometric 3d illustration of tiny futuristic city, clean vector style, pastel colors, miniature buildings, low poly, blender render, cute, white background", contentZh: "等距 3D 微型未来城市插画，干净矢量风格，粉彩色，微型建筑，低多边形，Blender 渲染，可爱，白底", tags: ["3D渲染", "等距", "城市", "低多边形"], model: "stable-diffusion" },
  { title: "极简几何雕塑", content: "minimalist 3d render of abstract geometric sculpture, soft pastel gradient, smooth surfaces, soft shadows, octane, clean studio, modern art", contentZh: "极简 3D 渲染抽象几何雕塑，柔和粉彩渐变，光滑表面，柔阴影，Octane，干净影棚，现代艺术", tags: ["3D渲染", "极简", "几何", "雕塑"], model: "dall-e-3" },
  { title: "霓虹玻璃字体", content: "3d render of glass typography, iridescent neon letters, octane, dark background, soft reflections, premium, modern --ar 16:9 --v 6 --stylize 400", contentZh: "3D 玻璃字体渲染，虹彩霓虹字母，Octane，深色背景，柔和反射，高端，现代", tags: ["3D渲染", "字体", "玻璃", "霓虹"], model: "midjourney" },
  { title: "美食汉堡 3D 卡通", content: "stylized 3d cartoon burger character, big eyes, smiling, soft lighting, octane render, vibrant colors, playful, clean background, 8k", contentZh: "风格化 3D 卡通汉堡角色，大眼睛，微笑，柔和灯光，Octane 渲染，鲜艳色彩，俏皮，干净背景，8K", tags: ["3D渲染", "卡通", "汉堡", "可爱"], model: "flux" },
  { title: "微观细胞 3D 科学", content: "3d scientific render of human cell, dynamic nucleus, vibrant organelles, microscopic, medical visualization, octane, ultra detailed, 8k", contentZh: "人体细胞 3D 科学渲染，动态细胞核，鲜艳细胞器，微观，医学可视化，Octane，超精细，8K", tags: ["3D渲染", "科学", "细胞", "医学"], model: "stable-diffusion" },
  { title: "未来概念车 3D", content: "futuristic concept car 3d render, sleek aerodynamic, glowing accents, studio lighting, reflections, octane, automotive design, ultra detailed", contentZh: "未来概念车 3D 渲染，流线空气动力学，发光点缀，影棚灯光，反射，Octane，汽车设计，超精细", tags: ["3D渲染", "概念车", "未来", "汽车"], model: "dall-e-3" },
  { title: "柔光抽象球体", content: "abstract 3d render of floating glossy spheres, gradient pastel, soft studio light, octane, minimal, serene, premium --ar 1:1 --v 6 --stylize 400", contentZh: "抽象 3D 漂浮光泽球体渲染，粉彩渐变，柔和影棚光，Octane，极简，宁静，高端", tags: ["3D渲染", "抽象", "球体", "极简"], model: "midjourney" },
  { title: "香水瓶 3D 产品渲染", content: "luxury perfume bottle 3d product render, frosted glass, golden cap, soft studio lighting, water splash, octane, ultra realistic, 8k commercial", contentZh: "奢华香水瓶 3D 产品渲染，磨砂玻璃，金色瓶盖，柔和影棚灯光，水花，Octane，超写实，8K 商业", tags: ["3D渲染", "产品", "香水", "高端"], model: "flux" },
  // ===== 像素艺术 161-170 =====
  { title: "像素风奇幻村庄", content: "pixel art fantasy village, cozy cottages, market stalls, warm lantern light, 16 bit, detailed, game art, stardew valley style --ar 16:9 --v 6 --stylize 200", contentZh: "像素艺术奇幻村庄，温馨小屋，市场摊位，温暖灯笼光，16 位，精细，游戏美术，星露谷风格", tags: ["像素艺术", "奇幻", "村庄", "游戏"], model: "midjourney" },
  { title: "赛博朋克像素城", content: "pixel art cyberpunk city at night, neon signs, rain, flying cars, detailed, 16 bit, game art, retro, vibrant, atmospheric", contentZh: "像素艺术赛博朋克夜景城市，霓虹招牌，雨水，飞行汽车，精细，16 位，游戏美术，复古，鲜艳，氛围感", tags: ["像素艺术", "赛博朋克", "城市", "复古"], model: "flux" },
  { title: "像素风角色立绘", content: "pixel art character sprite, knight with sword, 32 bit, detailed shading, game asset, retro rpg style, vibrant, clean", contentZh: "像素艺术角色精灵，持剑骑士，32 位，精细阴影，游戏素材，复古 RPG 风格，鲜艳，干净", tags: ["像素艺术", "角色", "骑士", "游戏"], model: "stable-diffusion" },
  { title: "像素海滩日落", content: "pixel art beach sunset, palm trees, sailboat, ocean, warm gradient sky, 16 bit, retro game art, peaceful, detailed", contentZh: "像素艺术海滩日落，棕榈树，帆船，海洋，温暖渐变天空，16 位，复古游戏美术，宁静，精细", tags: ["像素艺术", "海滩", "日落", "复古"], model: "dall-e-3" },
  { title: "像素风太空冒险", content: "pixel art space adventure scene, astronaut on alien planet, two moons, strange plants, 16 bit, retro game, detailed, vibrant --ar 16:9 --v 6", contentZh: "像素艺术太空冒险场景，宇航员在外星球，两轮月亮，奇异植物，16 位，复古游戏，精细，鲜艳", tags: ["像素艺术", "太空", "冒险", "复古"], model: "midjourney" },
  { title: "像素咖啡馆内景", content: "pixel art cozy cafe interior, counter, plants, customers, warm light, 16 bit, detailed, game art, lo-fi aesthetic, charming", contentZh: "像素艺术温馨咖啡馆内景，柜台，植物，顾客，暖光，16 位，精细，游戏美术，lo-fi 美学，迷人", tags: ["像素艺术", "咖啡馆", "内景", "温馨"], model: "flux" },
  { title: "像素森林精灵", content: "pixel art forest elf, detailed, 32 bit, vibrant colors, game character, retro rpg, clean sprite, fantasy", contentZh: "像素艺术森林精灵，精细，32 位，鲜艳色彩，游戏角色，复古 RPG，干净精灵图，奇幻", tags: ["像素艺术", "精灵", "森林", "角色"], model: "stable-diffusion" },
  { title: "像素雪山小屋", content: "pixel art snowy mountain cabin, chimney smoke, pine trees, aurora sky, 16 bit, cozy, retro game art, detailed, peaceful", contentZh: "像素艺术雪山小屋，炊烟，松树，极光天空，16 位，温馨，复古游戏美术，精细，宁静", tags: ["像素艺术", "雪景", "小屋", "极光"], model: "dall-e-3" },
  { title: "像素街机游戏厅", content: "pixel art 80s arcade hall, neon cabinets, kids playing, retro vibe, 16 bit, detailed, nostalgic, game art --ar 16:9 --v 6 --stylize 200", contentZh: "像素艺术 80 年代街机厅，霓虹机台，游玩的孩子，复古氛围，16 位，精细，怀旧，游戏美术", tags: ["像素艺术", "街机", "复古", "怀旧"], model: "midjourney" },
  { title: "像素龙与城堡", content: "pixel art dragon attacking castle, knights, fire, dramatic sky, 16 bit, retro game, detailed, vibrant, epic", contentZh: "像素艺术巨龙攻城，骑士，火焰，戏剧化天空，16 位，复古游戏，精细，鲜艳，史诗", tags: ["像素艺术", "巨龙", "城堡", "史诗"], model: "flux" },
  // ===== 国风水墨 171-180 =====
  { title: "水墨武侠剑客", content: "chinese ink wash painting, lone swordsman on misty cliff, flowing robes, dynamic brush strokes, monochrome with red seal, xuan paper, wuxia --ar 9:16 --v 6 --stylize 300", contentZh: "中国水墨画，迷雾悬崖上的孤傲剑客，飘动衣袍，灵动笔触，单色配朱红印章，宣纸，武侠", tags: ["水墨", "武侠", "国风", "立绘"], model: "midjourney" },
  { title: "山水留白意境", content: "traditional chinese ink landscape, mountains and river, minimalist negative space, lone boat, mist, literati painting style, serene, atmospheric", contentZh: "传统中国水墨山水，山与河，极简留白，孤舟，雾气，文人画风格，宁静，富有意境", tags: ["水墨", "山水", "留白", "意境"], model: "flux" },
  { title: "工笔花鸟画", content: "gongbi fine brushwork painting of magpie on plum branch, intricate details, soft colors, traditional chinese, rice paper, elegant, masterpiece", contentZh: "工笔画，梅枝喜鹊，繁复细节，柔和色彩，传统中式，宣纸，优雅，杰作", tags: ["水墨", "工笔", "花鸟", "国风"], model: "stable-diffusion" },
  { title: "水墨仕女图", content: "traditional chinese ink painting of elegant lady in hanfu, flowing lines, soft washes, plum blossom, literati style, serene, detailed", contentZh: "传统中国水墨仕女图，汉服女子，流畅线条，柔和渲染，梅花，文人画风格，宁静，精细", tags: ["水墨", "仕女", "汉服", "国风"], model: "dall-e-3" },
  { title: "水墨奔马图", content: "chinese ink painting of galloping horses, dynamic splash ink, xu beihong style, monochrome, energetic brushwork, xuan paper --ar 16:9 --v 6 --stylize 300", contentZh: "中国水墨奔马图，动态泼墨，徐悲鸿风格，单色，有力笔触，宣纸", tags: ["水墨", "奔马", "泼墨", "国风"], model: "midjourney" },
  { title: "青绿山水画", content: "qing green blue landscape painting, layered mountains, pavilions, gold accents, traditional chinese, wang ximeng style, ornate, serene", contentZh: "青绿山水画，层叠山峦，楼阁，金箔点缀，传统中式，王希孟风格，华丽，宁静", tags: ["水墨", "青绿", "山水", "国风"], model: "flux" },
  { title: "水墨竹林隐士", content: "ink wash painting of hermit in bamboo grove, playing guqin, misty, minimalist, literati style, monochrome, serene, traditional chinese", contentZh: "水墨画，竹林隐士抚琴，雾气，极简，文人画风格，单色，宁静，传统中式", tags: ["水墨", "隐士", "竹林", "国风"], model: "stable-diffusion" },
  { title: "水墨游鱼图", content: "traditional chinese ink painting of koi fish swimming, dynamic brush strokes, water ripples, minimalist, zen, xuan paper, elegant", contentZh: "传统中国水墨游鱼图，灵动笔触，水波涟漪，极简，禅意，宣纸，优雅", tags: ["水墨", "游鱼", "禅意", "国风"], model: "dall-e-3" },
  { title: "泼墨山水长卷", content: "chinese splash ink landscape scroll, dramatic mountains, waterfalls, tiny figures, vast scale, traditional, atmospheric --ar 21:9 --v 6 --stylize 400", contentZh: "中国泼墨山水长卷，戏剧化山峦，瀑布，渺小人物，辽阔尺度，传统，富有氛围", tags: ["水墨", "泼墨", "长卷", "山水"], model: "midjourney" },
  { title: "水墨梅兰竹菊", content: "ink wash painting of four gentlemen plum orchid bamboo chrysanthemum, elegant brushwork, monochrome, traditional chinese, literati, serene", contentZh: "水墨四君子梅兰竹菊，优雅笔触，单色，传统中式，文人画，宁静", tags: ["水墨", "四君子", "文人", "国风"], model: "flux" },
  // ===== 极简主义 181-190 =====
  { title: "极简几何海报", content: "minimalist geometric poster, primary colors, bauhaus style, clean shapes, balanced composition, modern design, vector --ar 2:3 --v 6 --stylize 200", contentZh: "极简几何海报，三原色，包豪斯风格，干净形状，平衡构图，现代设计，矢量", tags: ["极简", "海报", "几何", "包豪斯"], model: "midjourney" },
  { title: "极简产品包装", content: "minimalist product packaging design, monochrome, clean typography placeholder, single accent color, modern, elegant, studio render", contentZh: "极简产品包装设计，单色，干净字体占位，单一强调色，现代，优雅，影棚渲染", tags: ["极简", "包装", "设计", "现代"], model: "flux" },
  { title: "极简单线人像", content: "minimalist one line art portrait of woman face, single continuous line, monochrome, elegant, modern, clean, on white background", contentZh: "极简单线人像，女性面孔，单一连续线条，单色，优雅，现代，干净，白底", tags: ["极简", "单线", "人像", "现代"], model: "stable-diffusion" },
  { title: "极简建筑摄影", content: "minimalist architecture photography, white concrete staircase against blue sky, single shadow, geometric, serene, fine art, ultra detailed", contentZh: "极简建筑摄影，蓝天下白色混凝土楼梯，单一阴影，几何，宁静，艺术，超精细", tags: ["极简", "建筑", "摄影", "几何"], model: "dall-e-3" },
  { title: "极简渐变背景", content: "minimalist gradient background, soft pastel, smooth, abstract, clean, modern, for ui hero section, premium --ar 16:9 --v 6 --stylize 200", contentZh: "极简渐变背景，柔和粉彩，平滑，抽象，干净，现代，适用于 UI 主视觉区，高端", tags: ["极简", "渐变", "背景", "UI"], model: "midjourney" },
  { title: "极简静物摄影", content: "minimalist still life, single ceramic vase with one branch, soft shadow, neutral background, zen, fine art photography, serene", contentZh: "极简静物，单枝花瓶，柔阴影，中性背景，禅意，艺术摄影，宁静", tags: ["极简", "静物", "禅意", "摄影"], model: "flux" },
  { title: "极简字体海报", content: "minimalist typographic poster, large sans serif letter, lots of negative space, monochrome with red dot, swiss style, modern", contentZh: "极简字体海报，巨大无衬线字母，大量留白，单色配红点，瑞士风格，现代", tags: ["极简", "字体", "海报", "瑞士"], model: "stable-diffusion" },
  { title: "极简抽象几何", content: "minimalist abstract geometric composition, two overlapping circles and a square, muted tones, balanced, modern art, clean, elegant", contentZh: "极简抽象几何构图，两个重叠圆与一个方形，低饱和色调，平衡，现代艺术，干净优雅", tags: ["极简", "抽象", "几何", "现代"], model: "dall-e-3" },
  { title: "极简风景剪影", content: "minimalist landscape, single tree on hill silhouette, gradient sunset sky, negative space, serene, fine art --ar 3:2 --v 6 --stylize 200", contentZh: "极简风景，山丘单树剪影，渐变落日天空，留白，宁静，艺术", tags: ["极简", "风景", "剪影", "落日"], model: "midjourney" },
  { title: "极简品牌名片", content: "minimalist business card mockup, clean layout, monochrome, single accent line, elegant typography, modern branding, studio render", contentZh: "极简名片原型，干净布局，单色，单一强调线，优雅字体，现代品牌，影棚渲染", tags: ["极简", "名片", "品牌", "现代"], model: "flux" },
  // ===== 超现实主义 191-200 =====
  { title: "梦境巨月剪影", content: "surreal dreamscape, giant glowing moon on horizon, lone silhouette on cliff, purple mist, ethereal, dali inspired, painterly, dreamlike --ar 4:3 --v 6 --stylize 600", contentZh: "超现实梦境，地平线上巨大发光月亮，悬崖孤影，紫色薄雾，空灵，达利风格，绘画感，梦幻", tags: ["超现实", "梦境", "月亮", "艺术"], model: "midjourney" },
  { title: "天空之鲸", content: "surreal scene of giant whale swimming through clouds above city, birds, soft light, dreamlike, magical realism, ultra detailed, cinematic", contentZh: "超现实场景，巨鲸在城市上空云中游动，飞鸟，柔和光线，梦幻，魔幻现实主义，超精细，电影感", tags: ["超现实", "鲸鱼", "天空", "魔幻"], model: "flux" },
  { title: "融化时钟荒原", content: "surreal landscape with melting clocks on dead tree branches, desert, dali inspired, dreamlike, soft light, detailed, masterpiece", contentZh: "超现实风景，枯树枝上融化时钟，沙漠，达利风格，梦幻，柔和光线，精细，杰作", tags: ["超现实", "达利", "时钟", "梦幻"], model: "stable-diffusion" },
  { title: "书籍飞鸟图书馆", content: "surreal library where books transform into birds and fly away, shafts of light, dreamlike, magical, intricate, detailed, rene magritte style", contentZh: "超现实图书馆，书籍化作飞鸟离巢，光柱，梦幻，魔法，繁复，精细，马格利特风格", tags: ["超现实", "图书馆", "飞鸟", "魔幻"], model: "dall-e-3" },
  { title: "悬浮海洋球体", content: "surreal floating sphere containing tiny ocean with waves and lighthouse, hovering over desert, dreamlike, dali inspired, ultra detailed --ar 1:1 --v 6 --stylize 600", contentZh: "超现实悬浮球体，内含微型海洋与灯塔波浪，悬浮于沙漠之上，梦幻，达利风格，超精细", tags: ["超现实", "球体", "海洋", "梦幻"], model: "midjourney" },
  { title: "颠倒森林世界", content: "surreal inverted forest world, trees hanging from sky, water flowing upward, dreamlike, magical realism, ultra detailed, cinematic, 8k", contentZh: "超现实颠倒森林世界，树木悬挂天空，水流向上，梦幻，魔幻现实主义，超精细，电影感，8K", tags: ["超现实", "颠倒", "森林", "魔幻"], model: "flux" },
  { title: "门中门异空间", content: "surreal endless doors floating in cosmic void, each opening to different world, dreamlike, intricate, magritte inspired, detailed, masterpiece", contentZh: "超现实无尽之门漂浮于宇宙虚空，每扇门通向不同世界，梦幻，繁复，马格利特风格，精细，杰作", tags: ["超现实", "门", "异空间", "魔幻"], model: "stable-diffusion" },
  { title: "云上城堡岛屿", content: "surreal castle on small floating island in pastel sky, waterfalls into clouds, birds, dreamlike, fairy tale, magical, highly detailed", contentZh: "超现实粉彩天空中小岛上的城堡，瀑布落入云海，飞鸟，梦幻，童话，魔法，超精细", tags: ["超现实", "城堡", "悬浮", "童话"], model: "dall-e-3" },
  { title: "镜面沙漠反射", content: "surreal desert with giant mirror reflecting different sky, lone figure, dreamlike, dali inspired, hyperrealistic, ultra detailed --ar 16:9 --v 6 --stylize 500", contentZh: "超现实沙漠，巨型镜子反射不同天空，孤独身影，梦幻，达利风格，超写实，超精细", tags: ["超现实", "镜子", "沙漠", "梦幻"], model: "midjourney" },
  { title: "时间漩涡城市", content: "surreal city swirling into a time vortex, buildings bending, clocks melting, dreamlike, cinematic, ultra detailed, magical realism, 8k", contentZh: "超现实城市卷入时间漩涡，建筑弯曲，时钟融化，梦幻，电影感，超精细，魔幻现实主义，8K", tags: ["超现实", "时间", "漩涡", "城市"], model: "flux" },
];

function modelConfig(model: Model) {
  return MODELS.find((m) => m.model === model)!;
}

function sourceFor(i: number): {
  source: "crawled" | "submitted" | "official";
  sourceUrl?: string;
} {
  const m = i % 20;
  if (m < 12) return { source: "crawled" };
  if (m < 17) return { source: "submitted" };
  return {
    source: "official",
    sourceUrl: OFFICIAL_URLS[i % OFFICIAL_URLS.length],
  };
}

export const imageSeeds: SeedPrompt[] = cores.map((c, i) => {
  const cfg = modelConfig(c.model);
  const { source, sourceUrl } = sourceFor(i);
  return {
    id: `img_${String(i + 1).padStart(3, "0")}`,
    title: c.title,
    content: c.content,
    contentEn: c.content,
    contentZh: c.contentZh,
    type: "image",
    model: cfg.model,
    vendor: cfg.vendor,
    params: cfg.params,
    tags: c.tags,
    language: "en",
    source,
    sourceUrl,
    hue: Math.round((i * 360) / cores.length) % 360,
    pattern: PATTERNS[i % PATTERNS.length],
    viewCount: 1000 + ((i * 1373) % 49000),
    copyCount: 100 + ((i * 877) % 9900),
    ratingAvg: RATINGS[i % RATINGS.length],
    ratingCount: 20 + ((i * 53) % 381),
    isFeatured: i % 5 === 0,
    status: "published",
    authorName: AUTHORS[i % AUTHORS.length],
    visibility: "public",
    createdDaysAgo: 1 + ((i * 7) % 90),
  };
});
